version: 2

jobs:
  test-1.13:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: make clean
      - run: make test
      - run: make lint

  test-1.14:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: make clean
      - run: make test
      - run: make lint

  test-latest:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: make clean
      - run: make test
      - run: make lint


