version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: make clean
      - run: make test
      - run: make lint
      - run: sh -c 'GOPROXY="https://proxy.golang.org" GO111MODULE=on go get "github.com/HeRCLab/wavegen" || true'


