version: 2

executors:
  linux:
    docker:
      - image: circleci/golang:1.14
      - image: circleci/golang:1.13
      - image: circleci/golang:latest

jobs:
  build:
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: make clean
      - run: make test
      - run: make lint

