version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.14
      - image: circleci/golang:1.13
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: make clean
      - run: make test
      - run: make lint

